domain_tags:
- business_priority: High
  data_sensitivity: PII Present
  tag_description: Data related to customer information, profiles, contact details,
    preferences, and customer relationship management. Includes master customer data,
    contact preferences, communication history, and customer segmentation information.
  tag_name: Customer_Management
- business_priority: High
  data_sensitivity: Business Critical
  tag_description: Operational data covering service delivery, logistics, crew management,
    scheduling, and move execution. Includes move orders, service tracking, resource
    allocation, and operational efficiency metrics.
  tag_name: Operations
- business_priority: Medium
  data_sensitivity: Marketing Sensitive
  tag_description: Marketing and lead generation data including lead sources, campaign
    tracking, opt-in preferences, and customer acquisition metrics. Used for marketing
    attribution, campaign effectiveness, and customer acquisition analysis.
  tag_name: Marketing
- business_priority: High
  data_sensitivity: Business Critical
  tag_description: Sales process data covering lead management, conversion tracking,
    sales pipeline, and revenue generation activities. Includes customer status, booking
    information, and sales performance metrics.
  tag_name: Sales
- business_priority: Medium
  data_sensitivity: Internal
  tag_description: Customer service and satisfaction data including service ratings,
    customer feedback, service quality metrics, and customer experience tracking for
    continuous improvement initiatives.
  tag_name: Customer_Service
- business_priority: High
  data_sensitivity: Internal
  tag_description: Logistics and transportation data covering move distances, routing,
    crew assignments, resource planning, and operational logistics for service delivery
    optimization and capacity planning.
  tag_name: Logistics
- business_priority: High
  data_sensitivity: Financial Sensitive
  tag_description: Financial and pricing data related to move costs, pricing models,
    revenue tracking, and financial performance metrics for business analysis and
    financial reporting purposes.
  tag_name: Financial
- business_priority: Medium
  data_sensitivity: Internal
  tag_description: Daily operational snapshots and reporting data used for day-to-day
    business operations, daily reporting, and operational decision making. Represents
    point-in-time operational views of business data.
  tag_name: Daily_Operations
