version: '3.4'
services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.3
    ports:
      - "${WEAVIATE_HTTP_PORT:-8080}:8080"    # REST API
      - "${WEAVIATE_GRPC_PORT:-50051}:50051" # gRPC API
    environment:
      QUERY_DEFAULTS_LIMIT: ${QUERY_DEFAULTS_LIMIT:-25}
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: '${AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED:-true}'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: '${DEFAULT_VECTORIZER_MODULE:-text2vec-aws}'
      ENABLE_MODULES: '${ENABLE_MODULES:-text2vec-aws}'
      AWS_REGION: '${AWS_REGION:-us-east-1}'
      AWS_ACCESS_KEY_ID: '${AWS_ACCESS_KEY_ID}'
      AWS_SECRET_ACCESS_KEY: '${AWS_SECRET_ACCESS_KEY}'
      CLUSTER_HOSTNAME: '${CLUSTER_HOSTNAME:-node1}'
    volumes:
      - weaviate_data:/var/lib/weaviate

volumes:
  weaviate_data: